services:
  z-manage:
    build: .
    ports:
      - "3103:3103"
    volumes:
      - ./data:/app/data
    environment:
      - PORT=3103
      - API_KEY=ab123168
      - DB_PATH=/app/data/z-manage.sqlite
    restart: unless-stopped
